---
title: "Model Recovery"
author: "Charlie Ludowici"
date: "8/8/2018"
output: github_document
---
##Truncated Normal
```{r warning=FALSE}
library(ggplot2)
rm(list = ls())
TNParamEstimates <- read.csv('EstimatesAndTruth/TruncNorm/estimatesAndTruthTruncNorm.csv', header = F)
TNParamLowerCI <- read.csv('EstimatesAndTruth/TruncNorm/estimatesAndTruthLowerBoundTruncNorm.csv', header = F)
TNParamUpperCI <- read.csv('EstimatesAndTruth/TruncNorm/estimatesAndTruthUpperBoundTruncNorm.csv', header = F)

colnames(TNParamEstimates) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'Efficacy',
  'Latency',
  'Precision'
)

colnames(TNParamLowerCI) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'EfficacyLower',
  'LatencyLower',
  'PrecisionLower'
)

colnames(TNParamUpperCI) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'EfficacyUpper',
  'LatencyUpper',
  'PrecisionUpper'
)

TNCIs <- cbind(TNParamLowerCI[,1:7], TNParamUpperCI[,5:7])



cor.test(TNParamEstimates$NonGuessingRate, TNParamEstimates$Efficacy)

ggplot(TNParamEstimates, aes(NonGuessingRate,Efficacy))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=TNCIs, aes(NonGuessingRate, ymin = EfficacyLower, ymax=EfficacyUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(TNParamEstimates$NonGuessingRate))+
  scale_y_continuous(breaks = unique(TNParamEstimates$NonGuessingRate))+
  geom_hline(yintercept = unique(TNParamEstimates$NonGuessingRate), linetype = 'dashed', alpha = .3)+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))


cor.test(TNParamEstimates$Mean, TNParamEstimates$Latency)

ggplot(TNParamEstimates, aes(Mean,Latency))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=TNCIs, aes(Mean, ymin = LatencyLower, ymax=LatencyUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(TNParamEstimates$Mean))+
  scale_y_continuous(breaks = c(2:3, unique(TNParamEstimates$Mean)))+
  geom_hline(yintercept = unique(TNParamEstimates$Mean), linetype = 'dashed', alpha = .3)+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))


cor.test(TNParamEstimates$SD, TNParamEstimates$Precision)

ggplot(TNParamEstimates, aes(SD,Precision))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=TNCIs, aes(SD, ymin = PrecisionLower, ymax=PrecisionUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(TNParamEstimates$SD))+
  scale_y_continuous(breaks = c(2:3, unique(TNParamEstimates$SD)))+
  geom_hline(yintercept = unique(TNParamEstimates$SD), linetype = 'dashed')+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))
```

##Log Normal
```{r warning=FALSE}
LNParamEstimates <- read.csv('EstimatesAndTruth/LogNorm/estimatesAndTruthLogNorm.csv', header = F)
LNParamLowerCI <- read.csv('EstimatesAndTruth/LogNorm/estimatesAndTruthLowerBoundLogNorm.csv', header = F)
LNParamUpperCI <- read.csv('EstimatesAndTruth/LogNorm/estimatesAndTruthUpperBoundLogNorm.csv', header = F)

colnames(LNParamEstimates) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'Shift',
  'Efficacy',
  'Latency',
  'Precision'
)

LNParamEstimates$Latency <- LNParamEstimates$Latency/(1000/12)
LNParamEstimates$Precision <- LNParamEstimates$Precision/(1000/12)

colnames(LNParamLowerCI) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'Shift',
  'EfficacyLower',
  'LatencyLower',
  'PrecisionLower'
)

colnames(LNParamUpperCI) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'Shift',
  'EfficacyUpper',
  'LatencyUpper',
  'PrecisionUpper'
)

LNCIs <- cbind(LNParamLowerCI[,1:8], LNParamUpperCI[,6:8])



cor.test(LNParamEstimates$NonGuessingRate, LNParamEstimates$Efficacy)

ggplot(LNParamEstimates, aes(NonGuessingRate,Efficacy))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=LNCIs, aes(NonGuessingRate, ymin = EfficacyLower, ymax=EfficacyUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(LNParamEstimates$NonGuessingRate))+
  scale_y_continuous(breaks = unique(LNParamEstimates$NonGuessingRate))+
  geom_hline(yintercept = unique(LNParamEstimates$NonGuessingRate), linetype = 'dashed', alpha = .3)+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))


cor.test(LNParamEstimates$Mean, LNParamEstimates$Latency)

ggplot(LNParamEstimates, aes(Mean,Latency))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=LNCIs, aes(Mean, ymin = LatencyLower, ymax=LatencyUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(LNParamEstimates$Mean))+
  scale_y_continuous(breaks = c(2:3, unique(LNParamEstimates$Mean)))+
  geom_hline(yintercept = unique(LNParamEstimates$Mean), linetype = 'dashed', alpha = .3)+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))


cor.test(LNParamEstimates$SD, LNParamEstimates$Precision)

ggplot(LNParamEstimates, aes(SD,Precision))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=LNCIs, aes(SD, ymin = PrecisionLower, ymax=PrecisionUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(LNParamEstimates$SD))+
  scale_y_continuous(breaks = c(2:3, unique(LNParamEstimates$SD)))+
  geom_hline(yintercept = unique(LNParamEstimates$SD), linetype = 'dashed')+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))
```

##Normal
```{r warning=FALSE}
NParamEstimates <- read.csv('EstimatesAndTruth/NormNorm/estimatesAndTruthNormNorm.csv', header = F)
NParamLowerCI <- read.csv('EstimatesAndTruth/NormNorm/estimatesAndTruthLowerBoundNormNorm.csv', header = F)
NParamUpperCI <- read.csv('EstimatesAndTruth/NormNorm/estimatesAndTruthUpperBoundNormNorm.csv', header = F)

colnames(NParamEstimates) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'Efficacy',
  'Latency',
  'Precision'
)

#NParamEstimates$Latency <- NParamEstimates$Latency/(1000/12)
#NParamEstimates$Precision <- NParamEstimates$Precision/(1000/12)

colnames(NParamLowerCI) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'EfficacyLower',
  'LatencyLower',
  'PrecisionLower'
)

colnames(NParamUpperCI) <-  c(
  'Participant',
  'NonGuessingRate',
  'Mean',
  'SD',
  'EfficacyUpper',
  'LatencyUpper',
  'PrecisionUpper'
)

NCIs <- cbind(NParamLowerCI[,1:7], NParamUpperCI[,5:7])



cor.test(NParamEstimates$NonGuessingRate, NParamEstimates$Efficacy)

ggplot(NParamEstimates, aes(NonGuessingRate,Efficacy))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=NCIs, aes(NonGuessingRate, ymin = EfficacyLower, ymax=EfficacyUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(NParamEstimates$NonGuessingRate))+
  scale_y_continuous(breaks = unique(NParamEstimates$NonGuessingRate))+
  geom_hline(yintercept = unique(NParamEstimates$NonGuessingRate), linetype = 'dashed', alpha = .3)+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))


cor.test(NParamEstimates$Mean, NParamEstimates$Latency)

ggplot(NParamEstimates, aes(Mean,Latency))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=NCIs, aes(Mean, ymin = LatencyLower, ymax=LatencyUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(NParamEstimates$Mean))+
  scale_y_continuous(breaks = c(2:3, unique(NParamEstimates$Mean)))+
  geom_hline(yintercept = unique(NParamEstimates$Mean), linetype = 'dashed', alpha = .3)+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))


cor.test(NParamEstimates$SD, NParamEstimates$Precision)

ggplot(NParamEstimates, aes(SD,Precision))+
  geom_point(colour = '#628093')+
  geom_errorbar(data=NCIs, aes(SD, ymin = PrecisionLower, ymax=PrecisionUpper),alpha = .2, width = .15,  inherit.aes = F, colour = '#628093')+
  stat_summary(fun.y = 'mean', geom='point', size = 4, colour = '#dca951')+
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = .2, colour = '#dca951')+
  scale_x_continuous(breaks = unique(NParamEstimates$SD))+
  scale_y_continuous(breaks = unique(NParamEstimates$SD))+
  geom_hline(yintercept = unique(NParamEstimates$SD), linetype = 'dashed')+
  theme(panel.background = element_blank(),axis.line = element_line(size = .5))


```