---
title: "nStreams Analysis"
author: "Charlie Ludowici"
date: "5/18/2017"
output: html_document
---

```{r}
library(ggplot2)
library(magrittr)
library(dplyr)
library(reshape2)
library(papaja)
library(truncnorm)
library(effsize)
theme_set(theme_apa(base_size = 15) ) 

savePlots <- T

posterior <- function(t, N1, N2=NULL, delta, lo=-Inf, hi = Inf,
                      priorMean=0,priorSD=1) {
        N = ifelse(is.null(N2), N1, N1*N2/(N1+N2))
        df  = ifelse(is.null(N2), N1 - 1, N1 + N2 - 2)
        
        #prior and likelihood
        #prior <- function(delta) dnorm(delta, priorMean, priorSD)*as.integer(delta >= lo)*as.integer(delta <= hi) 
        prior <- function(delta) dcauchy(delta, priorMean, priorSD)*as.integer(delta >= lo)*as.integer(delta <= hi) 
        K=1/integrate(prior,lower=lo,upper=hi)[[1]]
        f=function(delta) K*prior(delta)
        
        #(The as.integer bits above just provide bounds for the prior if you want them)
      
        likelihood <- function(delta) dt(t, df, delta*sqrt(N))
        
        #marginal likelihood
        marginal <- integrate(function(x) f(x)*likelihood(x), lo, hi)[[1]]
        
        #posterior
        post <- function(x) f(x)*likelihood(x) / marginal
        return(post(delta))
}


```

```{r message=FALSE}

null = 0

groups <- c('Endogenous','Exogenous')

latencyTN <- read.csv('../modelOutput/CSV/TGRSVP_Exp2_LatencyTruncNorm.csv')

precisionTN <- read.csv('../modelOutput/CSV/TGRSVP_Exp2_PrecisionTruncNorm.csv')

efficacyTN <- read.csv('../modelOutput/CSV/TGRSVP_Exp2_EfficacyTruncNorm.csv')

latencyN <- read.csv('../modelOutput/CSV/TGRSVP_Exp2_LatencyNorm.csv')

precisionN <- read.csv('../modelOutput/CSV/TGRSVP_Exp2_PrecisionNorm.csv')

efficacyN <- read.csv('../modelOutput/CSV/TGRSVP_Exp2_EfficacyNorm.csv')

allErrors <- read.csv('allErrors.csv', stringsAsFactors = F)
allErrors$subject <- gsub(' ','',allErrors$subject) #Why does python include a space after the ID?
allErrors <- allErrors[allErrors$subject!='AH',]

IDs <- unique(allErrors$subject)

BFs <- read.csv('../modelOutput/BF_ByParticipant.csv')

BFs$preferedModel <- ifelse(BFs$BF>3,'Buffering',ifelse(BFs$BF<.3,'Attention','Neither'))

```

```{r}
#Show trunc model fits

for(participant in IDs){
  for(group in groups){
    
    theseErrors <- allErrors[allErrors$subject==participant & allErrors$condition == group,]
    
    x = seq(min(theseErrors$responsePosRelative0),max(theseErrors$responsePosRelative0),.01)
    
    meanTN <- latencyTN %>% filter(., Participant == participant & Group == group) %>% pull(Estimate)/(1000/12)
    
    sdTN <- precisionTN %>% filter(., Participant == participant & Group == group) %>% pull(Estimate)/(1000/12)
    
    meanN <- latencyN %>% filter(., Participant == participant & Group == group) %>% pull(Estimate)/(1000/12)
    
    sdN <- precisionN %>% filter(., Participant == participant & Group == group) %>% pull(Estimate)/(1000/12)
    
    a = meanTN - sdTN
    if(a<0){
      a = 0
    }
    
    densTN <- dtruncnorm(x = x, a = a, b = Inf, mean = meanTN, sd = sdTN)
    
    densN <- dnorm(x = x, mean = meanN, sd = sdN)
    
    prefAttnModel <- BFs %>% filter(., Participant == participant & Group == group) %>% pull(preferedModel) == 'Attention'
    prefNeither <- BFs %>% filter(., Participant == participant & Group == group) %>% pull(preferedModel) == 'Neither'
    
    if(!prefNeither){
      colours <- c('green','red') #index this for plot colour. colours[1] is normal density colour. Green model is prefered
      if(prefAttnModel){
        colours <- rev(colours)
      }
    } else {
      colours = c('red','red')
    }
    
    thisData <- data.frame(x = x, norm = densN , Tnorm = densTN )
    
    show(ggplot(thisData, aes(x=x))+
      geom_line(aes(y = norm), colour = colours[1])+
      geom_line(aes(y=Tnorm), colour = colours[2])+
      geom_histogram(data = theseErrors, aes(x=responsePosRelative0, y=..density..), binwidth = 1, alpha=.5)+
      labs(title = paste0(participant,', ', group)))
  }
}
```

#Latency Analyses

```{r warning=FALSE}
tLatency <- t.test(data = latencyN,
                   Estimate~Group,
                   paired = T)
tLatency <- tLatency$statistic[[1]]

t  <- tLatency
N1 <- 6
N2 <- 6

priorMean = null
priorSD = sqrt(.5)

#examples of BF via savage-dickey ratio
#2-sided
BF10 = dcauchy(null,priorMean,priorSD) / posterior(tLatency, N1, delta=null,
                                              priorMean=priorMean,priorSD=priorSD)

#one-sided BF
BFplus = ( 2 * dcauchy(null,priorMean,priorSD) ) / posterior(tLatency, N1, delta=null, lo=0,
                                            priorMean=priorMean,priorSD=priorSD)

BF10
BFplus

delta  <- seq(-2, 6, .01)

posteriorAndPriorDF <- data.frame(delta = delta, posterior = posterior(t,N1,delta=delta, priorMean=priorMean,priorSD=priorSD), prior = dcauchy(delta, priorMean,priorSD))

posteriorMaxLatency <- optimize(function(delta) posterior(tLatency, N1, delta=delta, priorMean=priorMean, priorSD=priorSD), interval=c(-4,4),maximum = T)[[1]]

cohen.d(formula = Estimate~Group, data = latencyN, paired = T)

#This would only work for normal, we use Cauchy!
#credibleIntervalDensityLower <- mean(posteriorAndPriorDF$posterior)-sd(posteriorAndPriorDF$posterior)*1.96
#credibleIntervalDensityUpper <- mean(posteriorAndPriorDF$posterior)+sd(posteriorAndPriorDF$posterior)*1.96


latencyPlot <- ggplot(latencyN,aes(x=Group, y=Estimate))+
  geom_violin()+
  geom_line(aes(group=Participant, colour=Participant))+
  geom_point(aes(colour=Participant), size = 3)+
  scale_colour_brewer(palette = 'Spectral')+
  labs(x='Condition',y='Estimate (ms)',title='Latency')+
  theme(plot.title = element_text(hjust=.5))

show(latencyPlot)

latencyN %>% dcast(Participant~Group, value.var = 'Estimate') %>%
  ggplot(., aes(x=Exogenous, y=Endogenous))+
    geom_point(size = 4, aes(colour=ordered(1:6)))+
    scale_color_brewer(palette='Spectral', name='Participant')+
    lims(x=c(0,400), y=c(0,400))+
    labs(title='Latency Estimates (ms)')+
    theme(plot.title = element_text(size=15, hjust=.5))+
    annotate('text', x=100, y=325, label = paste0('BF10 = ', round(BF10,2)))+
    annotate('text', x = 100, y=305, label = paste0('Effect size = ', round(posteriorMaxLatency,2)))+
    geom_abline(intercept = 0, slope = 1,linetype='dashed')



latencyBayesPlot <- ggplot(posteriorAndPriorDF, aes(x=delta))+
  geom_line(aes(y=posterior, linetype = 'Posterior'))+
  geom_line(aes(y=prior, linetype = 'Prior'))+
  scale_linetype_manual(values = c('solid','dashed'),  guide = 'legend', name = NULL)+
  labs(x = expression(delta), y='Density', title = 'Latency Effect Size')

latencyBayesPlot
```

#Precision Analysis

```{r warning=FALSE}
frequentistTestPrecision <- t.test(data = precisionN,
                   Estimate~Group,
                   paired = T)
tPrecision <- frequentistTestPrecision$statistic[[1]]

t  <- tPrecision
N1 <- 10
N2 <- 10

priorMean =0
priorSD = sqrt(.5)

#examples of BF via savage-dickey ratio
#2-sided
BF10 = dcauchy(0,priorMean,priorSD) / posterior(tPrecision, N1, delta=0,
                                              priorMean=priorMean,priorSD=priorSD)

#one-sided BF
BFplus = ( 2 * dcauchy(0,priorMean,priorSD) ) / posterior(tPrecision, N1, delta=0, lo=0,
                                            priorMean=priorMean,priorSD=priorSD)

BF10
BFplus

delta  <- seq(-4, 2, .01)

posteriorModePrecision <- optimize(function(delta) posterior(tPrecision, N1, delta=delta,priorMean=priorMean,priorSD=priorSD), interval=c(-4,9),maximum = T)[[1]]

posteriorAndPriorDF <- data.frame(delta = delta, posterior = posterior(t,N1,delta=delta,
                                                                       priorMean=priorMean,priorSD=priorSD), prior = dcauchy(delta, priorMean,priorSD))



precisionPlot <- ggplot(precisionN,aes(x=Group, y=Estimate))+
  geom_violin()+
  geom_line(aes(group=Participant, colour=Participant))+
  geom_point(aes(colour=Participant),alpha=.8, size = 3)+
  scale_colour_brewer(palette = 'Spectral')+
  labs(x='Condition',y='Estimate (ms)',title='Precision')+
  theme(plot.title = element_text(hjust=.5))

show(precisionPlot)



precisionN %>% dcast(Participant~Group, value.var = 'Estimate') %>%
  ggplot(., aes(x=Exogenous, y=Endogenous, colour=ordered(1:6)))+
    geom_point(size = 4)+
    scale_color_brewer(palette='Spectral', name='Participant')+
    labs(title='Precision Estimates (ms)')+
    theme(plot.title = element_text(size=15, hjust=.5))+
    annotate('text', x=90, y=70, label = paste0('BF10 = ', round(BF10,2)))+
    annotate('text', x = 90, y=62, label = paste0('Effect size = ', round(posteriorModePrecision,2)))+
    geom_abline(intercept = 0, slope = 1,linetype='dashed')+
    lims(x = c(60, 200), y = c(60, 200))

precisionBayesPlot <- ggplot(posteriorAndPriorDF, aes(x=delta))+
  geom_line(aes(y=posterior, linetype = 'Posterior'))+
  geom_line(aes(y=prior, linetype = 'Prior'))+
  scale_linetype_manual(values = c('solid','dashed'),  guide = 'legend', name = NULL)+
  labs(x = expression(delta), y='Density', title = 'Precision Effect Size')


```

#Efficacy Analysis

```{r warning=FALSE}
frequentistTestEfficacy <-t.test(data = efficacyN,
                   Estimate~Group,
                   paired = T)
tEfficacy <- frequentistTestEfficacy$statistic[[1]]

t  <- tEfficacy
N1 <- 10
N2 <- 10

priorMean =0
priorSD = sqrt(.5)

#examples of BF via savage-dickey ratio
#2-sided
BF10 = dcauchy(0,priorMean,priorSD) / posterior(tEfficacy, N1, delta=0,
                                              priorMean=priorMean,priorSD=priorSD)

#one-sided BF
BFplus = ( 2 * dcauchy(0,priorMean,priorSD) ) / posterior(tEfficacy, N1, delta=0, lo=0,
                                            priorMean=priorMean,priorSD=priorSD)

BF10
BFplus

delta  <- seq(-2, 4, .01)

posteriorAndPriorDF <- data.frame(delta = delta, posterior = posterior(t,N1,delta=delta,
                                                                       priorMean=priorMean,priorSD=priorSD), prior = dcauchy(delta, priorMean,priorSD))

posteriorModeEfficacy <- optimize(function(delta) posterior(tEfficacy, N1, delta=delta,priorMean=priorMean,priorSD=priorSD), interval=c(-4,4),maximum = T)[[1]]


efficacyPlot <- ggplot(efficacyN, aes(x=Group, y=Estimate))+
  geom_violin()+
  stat_summary(fun.y = mean, geom = 'point', shape = 5, size = 5)+
  stat_summary(fun.data = mean_se, geom = 'errorbar', width = .1)+
  geom_line(aes(group=Participant, colour=Participant))+
  geom_point(aes(colour = Participant), size = 3, alpha = .6)+
  labs(x='Condition',y='Estimate',title='Efficacy')+
  theme(plot.title = element_text(hjust=.5))+
  scale_colour_brewer(palette = 'Spectral')

show(efficacyPlot)

efficacyN %>% dcast(Participant~Group, value.var = 'Estimate') %>%
  ggplot(., aes(x=Exogenous, y=Endogenous, colour=ordered(1:6)))+
    geom_point(size = 4)+
    scale_color_brewer(palette='Spectral', name='Participant')+
    lims(x=c(0,1), y=c(0,1))+
    labs(title='Efficacy Estimates [1 - P(Guess)]')+
    theme(plot.title = element_text(size=15, hjust=.5))+
    annotate('text', x=.8, y=.45, label = paste0('BF10 = ', round(BF10,2)))+
    annotate('text', x = .8, y=.37, label = paste0('Effect size = ', round(posteriorModeEfficacy,2)))+
    geom_abline(intercept = 0, slope = 1,linetype='dashed')



efficacyBayesPlot <- ggplot(posteriorAndPriorDF, aes(x=delta))+
  geom_line(aes(y=posterior, linetype = 'Posterior'))+
  geom_line(aes(y=prior, linetype = 'Prior'))+
  scale_linetype_manual(values = c('solid','dashed'),  guide = 'legend', name = NULL)+
  labs(x = expression(delta), y='Density', title = 'Efficacy Effect Size')

efficacyBayesPlot

```

```{r}

allParams <- rbind(efficacyN,latencyN,precisionN)


paramBar <- ggplot(allParams[!allParams$Parameter=='Efficacy',], aes(x=Parameter,y=Estimate, fill = Group))+
  stat_summary(geom='bar', fun.y = mean, position = position_dodge(.9))+
  stat_summary(geom='errorbar', fun.data=mean_se, position = position_dodge(.9), width = .3)+
  scale_fill_brewer(palette = 'Spectral')

paramBar


meanLatencyEndogenous <- allParams %>% filter(Group == 'Endogenous' & Parameter == 'Latency') %>% pull(Estimate) %>% mean
meanLatencyExogenous <- allParams %>% filter(Group == 'Exogenous' & Parameter == 'Latency') %>% pull(Estimate) %>% mean

meanPrecisionEndogenous <- allParams %>% filter(Group == 'Endogenous' & Parameter == 'Precision') %>% pull(Estimate) %>% mean
meanPrecisionExogenous <- allParams %>% filter(Group == 'Exogenous' & Parameter == 'Precision') %>% pull(Estimate) %>% mean

predictionPlot <- ggplot()+
  stat_function(data=data.frame(x=c(-400:800)/83.33), aes(x, fill = 'Peripheral'), fun = dnorm, args = list(mean = meanLatencyExogenous/83.33, sd = meanPrecisionExogenous/83.33), geom='area', alpha = .9)+
  stat_function(data=data.frame(x=c(-400:800)/83.33), aes(x, fill = 'Central'), fun = dnorm, args = list(mean = meanLatencyEndogenous/83.33, sd = meanPrecisionEndogenous/83.33), geom='area', alpha = .9)+
  scale_fill_manual(values=c('Central' = '#628093', 'Peripheral' = '#dca951'))+
  scale_x_continuous(breaks = -3:8,limits = c(-3,8))+
  labs(x='SPE', y=NULL, fill = 'Condition')

predictionPlot

# 
# if(savePlots){
#   ggsave(precisionPlot, file = 'precisionViolin.png', height=15, width=20,units='cm')
#   ggsave(latencyPlot, file = 'latencyViolin.png', height=15, width=20,units='cm')
#   ggsave(efficacyPlot, file = 'efficacyViolin.png', height=15, width=20,units='cm')
#   
#   ggsave(precisionScatter, file = 'precisionScatter.png', height=15, width=20,units='cm')
#   ggsave(latencyScatter, file = 'latencyScatter.png', height=15, width=20,units='cm')
#   ggsave(efficacyScatter, file = 'efficacyScatter.png', height=15, width=20,units='cm')
#   
#   
#   ggsave(efficacyBayesPlot, file = 'efficacyEffectSize.png', height=15, width=20,units='cm')
#   ggsave(latencyBayesPlot, file = 'latencyEffectSize.png', height=15, width=20,units='cm')
#     ggsave(precisionBayesPlot, file = 'precisionEffectSize.png', height=15, width=20,units='cm')
# }
```